name: sync upstream branches
on:
  schedule:
     # every month 
    - cron:  '0 0 1 * *'
jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Rebase upstream branches
        run: |
          git config --global user.name 'johu'
          git config --global user.email '1102969+johu@users.noreply.github.com'

          # "git checkout master" is unnecessary, already here by default
          git pull --unshallow  # this option is very important, you would get
                                # complains about unrelated histories without it.
                                # (but actions/checkout@v2 can also be instructed
                                # to fetch all git depth right from the start)

          git remote add upstream https://github.com/quassel/quassel.git
          git fetch upstream

          git checkout master
          git rebase upstream/master
          git push -f origin master
